backend:
  name: git-gateway
  branch: main

media_folder: "img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "pricing"
    label: "Pricing & Packages"
    files:
      - file: "content/pricing.json"
        label: "Website Pricing"
        name: "website_pricing"
        fields:
          - label: "Starter Package Price"
            name: "starter_price"
            widget: "string"

          - label: "Standard Package Price"
            name: "standard_price"
            widget: "string"

          - label: "Custom Package Price"
            name: "custom_price"
            widget: "string"
